# Generated by Django 5.0.6 on 2025-01-11 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='des',
            field=models.TextField(db_column='description'),
        ),
    ]
