# Generated by Django 5.0.6 on 2025-01-11 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_notice_des'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flat',
            old_name='mobile_number',
            new_name='mobile',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='name',
        ),
    ]
