# Generated by Django 5.0.6 on 2025-01-11 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_amenity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Amenity',
        ),
    ]
